import AppLayout from '@/Layouts/AppLayout';
import PageHeader from '@/Components/PageHeader';
import { Head, Link } from '@inertiajs/react';

type Domain = { id: number; name: string; status: string; registered_at: string | null; expires_at: string | null; nameservers: string[]; provider_status: string | null; registration_contacts: { registrant?: string } };

export default function Show({ domain }: { domain: Domain }) {
    return <AppLayout title={domain.name}><Head title={domain.name} /><PageHeader eyebrow="Domain Control Center" title={domain.name} description="Read-only domain information from your registrar-backed account." /><section className="max-w-4xl space-y-5"><div className="rounded-xl border border-[#e5e5e5] bg-white p-5"><div><p className="text-sm text-[#737373]">Lifecycle status</p><p className="mt-1 font-semibold">{domain.status}</p></div><dl className="mt-6 grid gap-4 text-sm sm:grid-cols-2"><div><dt className="text-[#737373]">Registered</dt><dd className="mt-1 font-medium">{domain.registered_at ?? 'Unknown'}</dd></div><div><dt className="text-[#737373]">Expires</dt><dd className="mt-1 font-medium">{domain.expires_at ?? 'Unknown'}</dd></div><div><dt className="text-[#737373]">Provider status</dt><dd className="mt-1 font-medium">{domain.provider_status ?? 'Unknown'}</dd></div><div><dt className="text-[#737373]">Registrant</dt><dd className="mt-1 font-medium">{domain.registration_contacts.registrant ?? 'Protected'}</dd></div></dl></div><div className="rounded-xl border border-[#e5e5e5] bg-white p-5"><h2 className="font-semibold">Nameservers</h2><div className="mt-3 space-y-2 text-sm">{domain.nameservers.map((nameserver) => <p key={nameserver} className="rounded-md bg-[#fafafa] px-3 py-2 font-mono">{nameserver}</p>)}</div></div><div className="rounded-xl border border-[#e5e5e5] bg-white p-5 text-sm text-[#525252]">Renewal, transfers, privacy, SSL, and DNS management will be available in later milestones.</div><Link href={route('domains')} className="inline-block text-sm underline">Back to My Domains</Link></section></AppLayout>;
}
