<?php

namespace App\Integrations\OnlineNic\Ote;

final class OteValidationReporter
{
    /** @var list<array{operation:string,result:string,code:string,behavior:string,notes:string,change:string}> */
    private array $rows = [];

    public function add(string $operation, string $result, ?int $providerCode, string $behavior, string $notes = '', string $change = 'No'): void
    {
        $this->rows[] = compact('operation', 'result', 'behavior', 'notes', 'change') + ['code' => $providerCode === null ? '' : (string) $providerCode];
    }

    /** @return list<array{operation:string,result:string,code:string,behavior:string,notes:string,change:string}> */
    public function rows(): array
    {
        return $this->rows;
    }

    public function markdown(string $title = 'OnlineNIC OTE validation results'): string
    {
        $lines = ['# '.$title, '', 'Generated by `onlinenic:ote-validate`. No credentials, contact IDs, auth codes, CSR material, or raw XML are included.', '', '| Operation | Result | Provider code | Observed normalized behavior | Notes | Implementation change required? |', '|---|---|---:|---|---|---|'];
        foreach ($this->rows as $row) {
            $lines[] = '| '.$this->cell($row['operation']).' | '.$this->cell($row['result']).' | '.$this->cell($row['code']).' | '.$this->cell($row['behavior']).' | '.$this->cell($row['notes']).' | '.$this->cell($row['change']).' |';
        }

        return implode("\n", $lines)."\n";
    }

    private function cell(string $value): string
    {
        return str_replace(['|', "\r", "\n"], ['\\|', '', ' '], $value);
    }
}
