import AppLayout from '@/Layouts/AppLayout';
import PageHeader from '@/Components/PageHeader';
import { Head, useForm } from '@inertiajs/react';
import { FormEvent } from 'react';

type Billing = { first_name: string; last_name: string; email: string; phone_number: string; country: string; city: string; street: string; state: string; postal_code: string };
type Quote = { domain: string; period: number; customerPrice: string; currency: string; availability: { domain: string }; capability: { periods: number[] } };
const emptyBilling = (): Billing => ({ first_name: '', last_name: '', email: '', phone_number: '', country: '', city: '', street: '', state: '', postal_code: '' });

export default function Domain({ quote, error }: { quote?: Quote | null; error?: string | null }) {
    const form = useForm({ domain: quote?.domain ?? '', period: quote?.period ?? 1, payment_billing: emptyBilling(), nameservers: ['', ''] });
    const submit = (event: FormEvent) => { event.preventDefault(); form.post(route('checkout.domain.store')); };
    const field = (name: keyof Billing, label: string, type = 'text') => <label className="block text-sm"><span className="mb-1 block font-medium text-[#525252]">{label}</span><input type={type} value={form.data.payment_billing[name]} onChange={(event) => form.setData('payment_billing', { ...form.data.payment_billing, [name]: event.target.value })} className="w-full rounded-md border border-[#d4d4d4] px-3 py-2" required /></label>;
    return <AppLayout title="Checkout"><Head title="Domain checkout" /><PageHeader eyebrow="Checkout" title="Complete domain registration" description="Your domain is checked again before this draft order is created." />{error && <div role="alert" className="mb-5 max-w-3xl rounded-md border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">{error}</div>}{quote && <form onSubmit={submit} className="grid max-w-5xl gap-6 lg:grid-cols-[1fr_320px]">
        <div className="space-y-6">
            <section className="rounded-xl border border-[#e5e5e5] bg-white p-5"><h2 className="text-lg font-semibold">Domain</h2><p className="mt-2 text-sm text-[#525252]">{quote.domain}</p><label className="mt-4 block text-sm"><span className="mb-1 block font-medium text-[#525252]">Registration period</span><select value={form.data.period} onChange={(event) => form.setData('period', Number(event.target.value))} className="rounded-md border border-[#d4d4d4] px-3 py-2">{quote.capability.periods.map((period) => <option key={period} value={period}>{period} year{period === 1 ? '' : 's'}</option>)}</select></label></section>
            <section className="rounded-xl border border-[#e5e5e5] bg-white p-5"><h2 className="text-lg font-semibold">Payment billing information</h2><p className="mt-1 text-sm text-[#737373]">Used for payment only, not registrar contacts.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{field('first_name', 'First name')}{field('last_name', 'Last name')}{field('email', 'Email', 'email')}{field('phone_number', 'Phone', 'tel')}{field('country', 'Country code')}{field('city', 'City')}{field('street', 'Street')}{field('state', 'State / province')}{field('postal_code', 'Postal code')}</div></section>
            <section className="rounded-xl border border-[#e5e5e5] bg-white p-5"><h2 className="text-lg font-semibold">Nameservers</h2><p className="mt-1 text-sm text-[#737373]">Provide at least two nameservers for this registration.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{form.data.nameservers.map((nameserver, index) => <label key={index} className="text-sm"><span className="mb-1 block font-medium text-[#525252]">Nameserver {index + 1}</span><input value={nameserver} onChange={(event) => { const next = [...form.data.nameservers]; next[index] = event.target.value; form.setData('nameservers', next); }} className="w-full rounded-md border border-[#d4d4d4] px-3 py-2" required /></label>)}</div></section>
        </div>
        <aside className="h-fit rounded-xl border border-[#e5e5e5] bg-white p-5 lg:sticky lg:top-6"><h2 className="font-semibold">Price summary</h2><div className="mt-4 flex justify-between text-sm"><span>{quote.domain}</span><span>{quote.period} year</span></div><div className="mt-5 flex justify-between border-t border-[#e5e5e5] pt-4 font-semibold"><span>Total</span><span>{quote.customerPrice} {quote.currency}</span></div><button type="submit" disabled={form.processing} className="mt-5 w-full rounded-md bg-[#171717] px-4 py-3 text-sm font-medium text-white disabled:opacity-50">{form.processing ? 'Creating draft…' : 'Create draft order'}</button><p className="mt-3 text-xs text-[#737373]">You will pay on the next step. Creating this order confirms the domain, period, billing information, and nameservers above.</p></aside>
    </form>}</AppLayout>;
}
