import React, { useMemo, useState } from 'react';
import { canShowDomainAction, lifecycleLabel, formatMoney, daysUntil, portfolioHealthSummary, attentionDomains, upcomingRenewals, filterDomains, renewalQuote, transferReadiness, portfolioDomainSummary, renewedExpirationDate } from './core.js';

const fullCaps = { canRenew:true, renewalYears:[1,2,3,5], supportsAutoRenew:true, supportsTransferLock:true, supportsTransferOut:true, supportsAuthCode:true, supportsPrivacy:true, supportsChildHosts:true, supportsChangeRegistrant:true, supportsSsl:true, supportsDelete:true };
const limitedCaps = { ...fullCaps, supportsPrivacy:false, supportsChildHosts:false, supportsChangeRegistrant:false, supportsDelete:false };
const seedDomains = [
  { id:'d1', name:'example.com', workspace:'Acme Studio', lifecycleStatus:'active', expiresAt:'2027-09-21', registeredAt:'2022-09-21', autoRenew:true, transferLock:'locked', privacyStatus:'active', sslStatus:'active', nameserverStatus:'configured', transfer:null, price:14.99, caps:fullCaps, nameservers:['ns1.example.net','ns2.example.net'] },
  { id:'d2', name:'northstar.io', workspace:'Acme Studio', lifecycleStatus:'expiring', expiresAt:'2026-09-26', registeredAt:'2024-09-26', autoRenew:true, transferLock:'locked', privacyStatus:'active', sslStatus:'active', nameserverStatus:'configured', transfer:null, paymentFailed:true, price:42, caps:fullCaps, nameservers:['ns1.platformdns.com','ns2.platformdns.com'] },
  { id:'d3', name:'orbitlabs.dev', workspace:'Labs', lifecycleStatus:'transfer_pending', expiresAt:'2027-01-11', registeredAt:'2025-01-11', autoRenew:false, transferLock:'unlocked', privacyStatus:'unsupported', sslStatus:'pending', nameserverStatus:'configured', transfer:'processing', price:18, caps:limitedCaps, nameservers:['ns1.vercel-dns.com','ns2.vercel-dns.com'] },
  { id:'d4', name:'madebyacme.co', workspace:'Acme Studio', lifecycleStatus:'active', expiresAt:'2027-05-02', registeredAt:'2023-05-02', autoRenew:true, transferLock:'locked', privacyStatus:'active', sslStatus:'inactive', nameserverStatus:'action_required', transfer:null, price:28, caps:fullCaps, nameservers:['ns1.oldhost.com','ns2.oldhost.com'] },
  { id:'d5', name:'framekit.app', workspace:'Labs', lifecycleStatus:'active', expiresAt:'2028-03-14', registeredAt:'2026-03-14', autoRenew:true, transferLock:'locked', privacyStatus:'active', sslStatus:'active', nameserverStatus:'configured', transfer:null, price:19, caps:fullCaps, nameservers:['ns1.platformdns.com','ns2.platformdns.com'] },
];

const nav = [ ['overview','Overview'], ['domains','Domains'], ['transfers','Transfers'], ['ssl','SSL'], ['billing','Billing'], ['workspace','Members'], ['settings','Settings'] ];
const tabs = ['overview','renewal','contacts','nameservers','privacy','security','transfers','ssl','billing','activity'];

export default function App(){
  const [route,setRoute]=useState('overview');
  const [domains,setDomains]=useState(seedDomains);
  const [domainId,setDomainId]=useState('d1');
  const [tab,setTab]=useState('overview');
  const [modal,setModal]=useState(null);
  const [cart,setCart]=useState([]);
  const domain=domains.find(d=>d.id===domainId) ?? domains[0];
  const openDomain=(id,nextTab='overview')=>{setDomainId(id);setTab(nextTab);setRoute('domain')};
  const updateDomain=patch=>setDomains(ds=>ds.map(d=>d.id===domainId?{...d,...patch}:d));
  return <div className="app">
    <Sidebar route={route} setRoute={setRoute} count={domains.length}/>
    <div className="shell"><Topbar route={route} domain={domain} setRoute={setRoute}/><main className="main">
      {route==='overview' && <Overview domains={domains} openDomain={openDomain} setRoute={setRoute}/>} 
      {route==='domains' && <Domains domains={domains} openDomain={openDomain} setRoute={setRoute}/>} 
      {route==='domain' && <DomainDetail domain={domain} tab={tab} setTab={setTab} updateDomain={updateDomain} setModal={setModal}/>} 
      {route==='transfers' && <Transfers openDomain={openDomain}/>} 
      {route==='ssl' && <SSL/>} 
      {route==='billing' && <Billing/>} 
      {route==='workspace' && <Workspace/>} 
      {route==='settings' && <Settings/>} 
      {route==='search' && <Search cart={cart} setCart={setCart} setRoute={setRoute}/>} 
      {route==='checkout' && <Checkout cart={cart} setCart={setCart} setRoute={setRoute}/>} 
    </main></div>
    {modal && <Modal config={modal} close={()=>setModal(null)}/>} 
  </div>;
}

function Sidebar({route,setRoute,count}){return <aside className="sidebar"><div className="brand"><span className="brand-mark">D</span><span>Domain Console</span></div><button className="workspace-switcher"><span className="left"><span className="workspace-icon">AC</span><span className="workspace-name">Acme Studio</span></span><span>⌄</span></button><div className="nav-label">Manage</div><nav className="nav">{nav.slice(0,5).map(([r,l])=><button key={r} className={`nav-item ${route===r||(r==='domains'&&route==='domain')?'active':''}`} onClick={()=>setRoute(r)} style={{border:0,textAlign:'left',width:'100%'}}><span>◌</span><span>{l}</span>{r==='domains'&&<span className="nav-count">{count}</span>}</button>)}</nav><div className="nav-label">Workspace</div><nav className="nav">{nav.slice(5).map(([r,l])=><button key={r} className={`nav-item ${route===r?'active':''}`} onClick={()=>setRoute(r)} style={{border:0,textAlign:'left',width:'100%'}}><span>◌</span><span>{l}</span></button>)}</nav><div className="sidebar-bottom"><div className="user-block"><span className="avatar">IM</span><span className="user-meta"><strong>Ibrahim</strong><span>ibrahim@example.com</span></span></div></div></aside>}
function Topbar({route,domain,setRoute}){return <header className="topbar"><span className="breadcrumb">{route==='domain'?`Domains / ${domain.name}`:route[0].toUpperCase()+route.slice(1)}</span><div className="topbar-actions"><button className="search-trigger"><span>⌕</span><span className="search-copy">Search domains or actions…</span><kbd>⌘ K</kbd></button><button className="icon-btn">◌</button><button className="btn primary" onClick={()=>setRoute('search')}>＋ <span className="mobile-hide">Buy domain</span></button></div></header>}
function PageHeader({title,description,actions}){return <div className="page-header"><div className="page-title"><h1>{title}</h1><p>{description}</p></div><div className="header-actions">{actions}</div></div>}
function Badge({children,tone=''}){return <span className={`badge ${tone}`}>{children}</span>}
function tone(status){return ({active:'success',expiring:'warning',transfer_pending:'info'})[status]||''}
function Metric({label,value,note}){return <div className="metric"><div className="metric-label"><span>{label}</span><span>›</span></div><div className="metric-value">{value}</div><div className="metric-note">{note}</div></div>}

function Overview({domains,openDomain,setRoute}){
  const health=portfolioHealthSummary(domains);
  const attention=attentionDomains(domains);
  const renewals=upcomingRenewals(domains,4);
  const autoRenewOn=domains.filter(d=>d.autoRenew).length;
  const healthPct=Math.round((health.healthy/Math.max(health.total,1))*100);
  return <>
    <div className="page-header dashboard-header"><div className="page-title"><span className="eyebrow">Portfolio</span><h1>Overview</h1><p>Everything that needs attention across your domains, renewals, transfers, security, and billing.</p></div><div className="header-actions"><button className="btn" onClick={()=>setRoute('transfers')}>Transfer domain</button><button className="btn primary" onClick={()=>setRoute('search')}>＋ Buy domain</button></div></div>
    <section className="metrics dashboard-metrics"><Metric label="Total domains" value={health.total} note="Across 2 workspaces"/><Metric label="Auto-renew" value={`${autoRenewOn}/${health.total}`} note={`${Math.round(autoRenewOn/health.total*100)}% coverage`}/><Metric label="Expiring soon" value={health.expiringSoon} note="Within 30 days"/><Metric label="Active transfers" value={health.transfersInProgress} note={health.transfersInProgress?'Registrar processing':'Nothing in progress'}/></section>
    <section className="portfolio-health card"><div className="health-main"><div className="health-copy"><span className="eyebrow">Portfolio health</span><div className="health-title-row"><h2>{health.healthy} of {health.total} domains are clear</h2><Badge tone={health.attention?'warning':'success'}>{healthPct}% healthy</Badge></div><p>Healthy domains need no registrar action. Processing transfers are tracked separately from issues that need you.</p></div><div className="health-score"><strong>{health.attention}</strong><span>need attention</span></div></div><div className="health-bar"><span className="health-segment healthy" style={{width:`${health.healthy/health.total*100}%`}}/><span className="health-segment processing" style={{width:`${health.transfersInProgress/health.total*100}%`}}/><span className="health-segment attention" style={{width:`${health.attention/health.total*100}%`}}/></div><div className="health-legend"><span><i className="legend-dot healthy"/>{health.healthy} healthy</span><span><i className="legend-dot processing"/>{health.transfersInProgress} processing</span><span><i className="legend-dot attention"/>{health.attention} attention</span></div></section>
    <div className="dashboard-grid"><div className="dashboard-main-column"><section className="card attention-card"><div className="card-header"><div><span className="eyebrow">Priority</span><h2>Needs attention</h2></div><span className="card-count">{attention.length}</span></div><div className="attention-list">{attention.map(({domain,state})=><div className="attention-row" key={domain.id}><div className={`attention-symbol ${state.tone}`}>!</div><div className="attention-copy"><div className="attention-title"><strong>{domain.name}</strong><Badge tone={state.tone}>{state.title}</Badge></div><p>{state.message}</p><span>{daysUntil(domain.expiresAt)} days until expiration · {domain.workspace}</span></div><div className="attention-action"><button className="btn small" onClick={()=>state.kind==='payment_failed'?setRoute('billing'):openDomain(domain.id,state.kind==='nameserver_issue'?'nameservers':'renewal')}>{state.kind==='payment_failed'?'Fix payment':'Review'}</button></div></div>)}</div></section><section className="card"><div className="card-header"><div><span className="eyebrow">Portfolio</span><h2>Recent domains</h2></div><button className="btn ghost small card-action" onClick={()=>setRoute('domains')}>View all ›</button></div><DomainTable domains={domains.slice(0,5)} compact onOpen={openDomain}/></section></div>
    <aside className="dashboard-side-column"><section className="card quick-card"><div className="card-header"><div><span className="eyebrow">Shortcuts</span><h2>Quick actions</h2></div></div><div className="quick-grid"><QuickTile title="Buy domain" desc="Search and register a new domain" symbol="＋" onClick={()=>setRoute('search')}/><QuickTile title="Transfer in" desc="Move an existing domain" symbol="⇄" onClick={()=>setRoute('transfers')}/><QuickTile title="Billing" desc="Renewals and payment methods" symbol="▣" onClick={()=>setRoute('billing')}/><QuickTile title="Invite member" desc="Add someone to this workspace" symbol="＋" onClick={()=>setRoute('workspace')}/></div></section><section className="card renewal-card"><div className="card-header"><div><span className="eyebrow">Next up</span><h2>Upcoming renewals</h2></div><button className="btn ghost small card-action" onClick={()=>setRoute('billing')}>Billing ›</button></div><div className="renewal-list">{renewals.map(({domain,daysRemaining})=><button className="renewal-row" key={domain.id} onClick={()=>openDomain(domain.id,'renewal')}><div className="renewal-date"><strong>{new Date(domain.expiresAt).toLocaleDateString('en-US',{month:'short',day:'numeric'})}</strong><span>{daysRemaining}d</span></div><div className="renewal-copy"><strong>{domain.name}</strong><span>{formatMoney(domain.price)} / year</span></div><div className="renewal-state"><Badge tone={domain.paymentFailed?'danger':daysRemaining<=30?'warning':domain.autoRenew?'success':''}>{domain.paymentFailed?'Payment failed':domain.autoRenew?'Auto-renew on':'Auto-renew off'}</Badge></div></button>)}</div></section><section className="card"><div className="card-header"><div><span className="eyebrow">Workspace</span><h2>Recent activity</h2></div></div><div className="card-body compact-body"><Activity title="Nameserver update" detail="example.com · Completed" time="12 min ago"/><Activity title="Transfer started" detail="orbitlabs.dev · Processing" time="2h ago"/><Activity title="Auto-renew payment failed" detail="northstar.io · Action required" time="4h ago"/></div></section></aside></div>
  </>;
}
function QuickTile({title,desc,symbol,onClick}){return <button className="quick-tile" onClick={onClick}><span className="quick-icon">{symbol}</span><span className="quick-copy"><strong>{title}</strong><span>{desc}</span></span><span>›</span></button>}

function Activity({title,detail,time}){return <div className="activity-item"><div className="activity-mark">◌</div><div className="activity-main"><strong>{title}</strong><span>{detail}</span></div><span className="activity-time">{time}</span></div>}
function DomainTable({domains,compact=false,onOpen}){
  return <div className="table-wrap portfolio-table-wrap"><table className={`portfolio-table ${compact?'compact':''}`}><thead><tr>{compact?<><th>Domain</th><th>Status</th><th>Expiry</th><th>Renewal</th></>:<><th>Domain</th><th>Lifecycle</th><th>Renewal</th><th>Security</th><th>Services</th><th>Workspace</th></>}<th/></tr></thead><tbody>{domains.map(d=>{const attention=d.paymentFailed?'Payment failed':d.nameserverStatus==='action_required'?'Nameservers need review':'No action required';return <tr key={d.id} className="clickable domain-row" onClick={()=>onOpen(d.id)}><td><div className="domain-identity-cell"><span className="domain-monogram">{d.name[0].toUpperCase()}</span><span><strong className="domain-cell">{d.name}</strong><span className="domain-sub">{compact?d.workspace:attention}</span></span></div></td><td><Badge tone={tone(d.lifecycleStatus)}>{lifecycleLabel(d.lifecycleStatus)}</Badge></td><td><div className="table-primary">{new Date(d.expiresAt).toLocaleDateString()}</div><div className="domain-sub">{daysUntil(d.expiresAt)} days</div></td>{compact?<td>{d.paymentFailed?<Badge tone="danger">Payment failed</Badge>:<Badge tone={d.autoRenew?'success':''}>{d.autoRenew?'Auto-renew':'Manual'}</Badge>}</td>:<><td><div className="security-inline"><span>⌁</span><span>{d.transferLock==='locked'?'Locked':'Unlocked'}</span></div><div className="domain-sub">Auth code {d.caps.supportsAuthCode?'protected':'unavailable'}</div></td><td><div className="service-pills"><span className={`service-pill ${d.privacyStatus==='active'?'good':''}`}>Privacy {d.privacyStatus==='unsupported'?'—':d.privacyStatus==='active'?'On':'Off'}</span><span className={`service-pill ${d.sslStatus==='active'?'good':d.sslStatus==='pending'?'info':''}`}>SSL {d.sslStatus}</span></div></td><td><div className="table-primary">{d.workspace}</div></td></>}<td className="row-arrow">›</td></tr>})}</tbody></table></div>
}

function Domains({domains,openDomain,setRoute}){
  const [q,setQ]=useState('');
  const [status,setStatus]=useState('all');
  const [workspace,setWorkspace]=useState('all');
  const summary=portfolioDomainSummary(domains);
  const filtered=useMemo(()=>filterDomains(domains,{query:q,status,workspace}),[domains,q,status,workspace]);
  const workspaces=[...new Set(domains.map(d=>d.workspace))];
  return <><div className="page-header domains-header"><div className="page-title"><span className="eyebrow">Portfolio</span><h1>Domains</h1><p>Search, review health, and manage every registrar capability from one portfolio.</p></div><div className="header-actions"><button className="btn" onClick={()=>setRoute('transfers')}>Transfer domain</button><button className="btn primary" onClick={()=>setRoute('search')}>＋ Buy domain</button></div></div><section className="domains-summary card"><PortfolioStat label="Total" value={summary.total} note="Across 2 workspaces"/><PortfolioStat label="Active" value={summary.active} note="Lifecycle active"/><PortfolioStat label="Auto-renew" value={`${summary.autoRenewOn}/${summary.total}`} note={`${Math.round(summary.autoRenewOn/Math.max(summary.total,1)*100)}% coverage`}/><PortfolioStat label="Transfer lock" value={summary.locked} note="Domains protected"/><PortfolioStat label="Needs attention" value={summary.attention} note={`${summary.expiring} expiring · ${summary.transferPending} transferring`} attention={summary.attention>0}/></section><section className="card domains-portfolio-card"><div className="domains-toolbar"><label className="input-shell domain-search-input">⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search domains…"/></label><select className="select" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All lifecycle states</option><option value="active">Active</option><option value="expiring">Expiring</option><option value="transfer_pending">Transfer pending</option></select><select className="select" value={workspace} onChange={e=>setWorkspace(e.target.value)}><option value="all">All workspaces</option>{workspaces.map(w=><option key={w}>{w}</option>)}</select><span className="toolbar-spacer"/><span className="results-count">{filtered.length} domains</span><button className="btn small">Export</button></div><DomainTable domains={filtered} onOpen={openDomain}/></section></>
}
function PortfolioStat({label,value,note,attention=false}){return <div className={`portfolio-stat ${attention?'attention':''}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></div>}

function DomainDetail({domain,tab,setTab,updateDomain,setModal}){
  const attention=domain.paymentFailed?{tone:'danger',label:'Action required',title:'Payment failed'}:domain.nameserverStatus==='action_required'?{tone:'warning',label:'Review',title:'Nameservers need review'}:domain.lifecycleStatus==='transfer_pending'?{tone:'info',label:'Processing',title:'Transfer processing'}:{tone:'success',label:'Clear',title:'No action required'};
  return <><button className="back-link">‹ Back to domains</button><section className="domain-control-hero"><div className="domain-control-main"><div className="domain-identity-head"><span className="domain-hero-icon">{domain.name[0].toUpperCase()}</span><div><span className="eyebrow">Domain control center</span><div className="domain-title-row"><h1>{domain.name}</h1><Badge tone={tone(domain.lifecycleStatus)}>{lifecycleLabel(domain.lifecycleStatus)}</Badge></div><p>{domain.workspace} · Registered {new Date(domain.registeredAt).toLocaleDateString()}</p></div></div><div className="header-actions domain-hero-actions"><button className="btn primary" onClick={()=>setTab('renewal')}>Renew domain</button></div></div><div className="domain-control-kpis"><ControlKpi label="Expires" value={new Date(domain.expiresAt).toLocaleDateString()} note={`${daysUntil(domain.expiresAt)} days remaining`}/><ControlKpi label="Auto-renew" value={domain.autoRenew?'Enabled':'Disabled'} note={domain.paymentFailed?'Payment action required':'Visa •••• 4242'}/><ControlKpi label="Transfer lock" value={domain.transferLock==='locked'?'Locked':'Unlocked'} note={domain.transferLock==='locked'?'Protected from transfer':'Transfer-out possible'}/><ControlKpi label="Domain health" value={attention.label} note={attention.title} tone={attention.tone}/></div></section>{(domain.paymentFailed||domain.lifecycleStatus==='transfer_pending'||domain.nameserverStatus==='action_required')&&<DomainAlert domain={domain} setTab={setTab}/>}<div className="domain-tabs-wrap"><nav className="domain-tabs">{tabs.map(t=><button className={`tab ${tab===t?'active':''}`} key={t} onClick={()=>setTab(t)}>{t[0].toUpperCase()+t.slice(1)}</button>)}</nav></div><section className="tab-panel"><DomainTab domain={domain} tab={tab} setTab={setTab} updateDomain={updateDomain} setModal={setModal}/></section></>
}
function ControlKpi({label,value,note,tone=''}){return <div className={tone?`domain-health-kpi ${tone}`:''}><span>{label}</span><strong>{value}</strong><small>{note}</small></div>}

function DomainAlert({domain,setTab}){if(domain.paymentFailed)return <div className="alert danger"><div className="alert-icon">!</div><div className="alert-copy"><div className="alert-title">Auto-renew failed</div><div className="alert-text">Update your payment method to avoid expiration in {daysUntil(domain.expiresAt)} days.</div></div><button className="btn small">Fix payment</button></div>;if(domain.lifecycleStatus==='transfer_pending')return <div className="alert info"><div className="alert-icon">↔</div><div className="alert-copy"><div className="alert-title">Transfer is processing</div><div className="alert-text">No action is currently required.</div></div><button className="btn small" onClick={()=>setTab('transfers')}>View transfer</button></div>;return <div className="alert warning"><div className="alert-icon">!</div><div className="alert-copy"><div className="alert-title">Nameserver configuration needs attention</div><div className="alert-text">One or more configured nameservers are not responding as expected.</div></div><button className="btn small" onClick={()=>setTab('nameservers')}>Review</button></div>}
function DomainTab(props){const map={overview:DomainOverview,renewal:Renewal,contacts:Contacts,nameservers:Nameservers,privacy:Privacy,security:Security,transfers:DomainTransfers,ssl:DomainSSL,billing:DomainBilling,activity:DomainActivity};const C=map[props.tab]||DomainOverview;return <C {...props}/>}
function StatusGrid({items}){return <div className="status-grid">{items.map(([a,b,c])=><div className="status-cell" key={a}><div className="status-label">{a}</div><div className="status-value">{b}</div><div className="status-sub">{c}</div></div>)}</div>}
function DomainOverview({domain,setTab,updateDomain,setModal}){return <><StatusGrid items={[["Registration",lifecycleLabel(domain.lifecycleStatus),'Registrar lifecycle'],['Expiration',new Date(domain.expiresAt).toLocaleDateString(),`${daysUntil(domain.expiresAt)} days remaining`],['Auto-renew',domain.autoRenew?'Enabled':'Disabled','Renewal preference'],['Transfer Lock',domain.transferLock,'Security state'],['Privacy',domain.privacyStatus,'ID Shield'],['Nameservers',domain.nameserverStatus,domain.nameservers.join(' · ')],['Transfer',domain.transfer||'None','Current transfer'],['SSL',domain.sslStatus,'Certificate product']]}/><div className="quick-actions"><button className="btn small" onClick={()=>setTab('renewal')}>Renew domain</button>{canShowDomainAction(domain.caps,'toggle_auto_renew')&&<button className="btn small" onClick={()=>updateDomain({autoRenew:!domain.autoRenew})}>{domain.autoRenew?'Disable':'Enable'} auto-renew</button>}{canShowDomainAction(domain.caps,domain.transferLock==='locked'?'unlock_domain':'lock_domain')&&<button className="btn small" onClick={()=>updateDomain({transferLock:domain.transferLock==='locked'?'unlocked':'locked'})}>{domain.transferLock==='locked'?'Unlock':'Lock'} domain</button>}<button className="btn small" onClick={()=>setTab('nameservers')}>Change nameservers</button><button className="btn small" onClick={()=>setTab('contacts')}>Edit contacts</button>{canShowDomainAction(domain.caps,'manage_privacy')&&<button className="btn small" onClick={()=>setTab('privacy')}>Manage privacy</button>}{canShowDomainAction(domain.caps,'get_auth_code')&&<button className="btn small" onClick={()=>setModal(authModal())}>Get auth code</button>}</div><div className="grid-2"><div><div className="section-title"><h2>DNS</h2></div><div className="card"><div className="setting-row"><div className="setting-copy"><strong>Nameservers</strong><span>{domain.nameservers.join(' · ')}</span></div><button className="btn small" onClick={()=>setTab('nameservers')}>View nameservers</button></div><div className="setting-row"><div className="setting-copy"><strong>DNS Zone</strong><span>Managed externally. DNS CRUD is not exposed in confirmed v1.</span></div><Badge>External</Badge></div></div></div><div><div className="section-title"><h2>Portfolio</h2></div><div className="card"><div className="card-body"><Def label="Workspace" value={domain.workspace}/><Def label="Registered" value={new Date(domain.registeredAt).toLocaleDateString()}/><Def label="Renewal price" value={formatMoney(domain.price)}/><Def label="Provider state" value="Synchronized"/></div></div></div></div></>}
function Def({label,value}){return <div className="definition"><dt>{label}</dt><dd>{value}</dd></div>}
function Renewal({domain,updateDomain}){
  const [processing,setProcessing]=useState(false);
  const [years,setYears]=useState(domain.caps.renewalYears[0]);
  const quote=renewalQuote(domain,years);
  const renew=()=>{setProcessing(true);setTimeout(()=>{updateDomain({expiresAt:renewedExpirationDate(domain.expiresAt,years),paymentFailed:false});setProcessing(false)},800)};
  return <div className="renewal-layout"><div className="renewal-main-column"><section className="card renewal-control-card"><div className="card-header"><div><span className="eyebrow">Renewal</span><h2>Renew {domain.name}</h2></div><Badge tone={domain.autoRenew?'success':''}>{domain.autoRenew?'Auto-renew enabled':'Manual renewal'}</Badge></div><div className="renewal-expiry-block"><div><span>Current expiration</span><strong>{new Date(domain.expiresAt).toLocaleDateString()}</strong><small>{daysUntil(domain.expiresAt)} days remaining</small></div><div className="renewal-expiry-meter"><span style={{width:`${Math.max(8,Math.min(100,daysUntil(domain.expiresAt)/365*100))}%`}}/></div></div>{domain.paymentFailed&&<div className="inline-warning danger"><span>!</span><div><strong>Last auto-renew attempt failed</strong><small>Update the payment method before the next attempt.</small></div><button className="btn small">Fix payment</button></div>}<div className="renewal-builder"><div className="field"><label>Renewal period</label><select value={years} onChange={e=>setYears(Number(e.target.value))}>{domain.caps.renewalYears.map(y=><option key={y} value={y}>{y} year{y>1?'s':''}</option>)}</select><small>Available periods are controlled by this TLD.</small></div><div className="renewal-total"><span>Total today</span><strong>{formatMoney(quote.total)}</strong><small>{formatMoney(quote.unitPrice)} / year × {quote.years}</small></div></div><div className="renewal-actions"><button className="btn primary" onClick={renew} disabled={processing}>{processing?'Processing…':`Renew for ${years} year${years>1?'s':''}`}</button><button className="btn" onClick={()=>updateDomain({autoRenew:!domain.autoRenew})}>{domain.autoRenew?'Disable':'Enable'} auto-renew</button></div></section><section className="card"><div className="card-header"><div><span className="eyebrow">History</span><h2>Renewal activity</h2></div></div><div className="card-body"><Activity title="Domain renewal" detail="Completed · 1 year" time="Sep 21, 2025"/></div></section></div><aside className="renewal-side-column"><section className="card renewal-details-card"><div className="card-header"><h2>Renewal details</h2></div><div className="card-body"><Def label="Customer renewal price" value={`${formatMoney(domain.price)} / year`}/><Def label="Payment method" value="Visa •••• 4242"/><Def label="Auto-renew" value={domain.autoRenew?'Enabled':'Disabled'}/><Def label="Last renewal attempt" value={domain.paymentFailed?'Failed · Today':'Completed · Sep 21, 2025'}/></div></section><section className="renewal-help"><span className="domain-action-icon">◌</span><div><strong>Renewal protection</strong><p>Ambiguous registrar writes stay processing until reconciled.</p></div></section></aside></div>
}

function Contacts({domain,setModal}){const cards=[['Registrant','Ahmed Mohamed','ahmed@example.com'],['Administrative','Ahmed Mohamed','ahmed@example.com'],['Technical','Company IT','it@acme.com'],['Billing','Finance Team','finance@acme.com']];return <div className="contact-grid">{cards.map(([type,name,email],i)=><div className="contact-card" key={type}><div className="contact-top"><span className="contact-type">{type}</span><div><button className="btn ghost small">Edit</button>{i===0&&domain.caps.supportsChangeRegistrant&&<button className="btn ghost small" onClick={()=>setModal({title:'Change Registrant',subtitle:'Distinct high-impact registrar operation.',body:'Registry verification may be required.'})}>Change Registrant</button>}</div></div><h3>{name}</h3><p>{email}</p></div>)}</div>}
function Nameservers({domain,setModal}){return <><div className="grid-2"><div className="card"><div className="card-header"><h2>Current Nameservers</h2><button className="btn small card-action" onClick={()=>setModal({title:'Change Nameservers',subtitle:'High-impact registrar operation.',body:domain.nameservers.join(' / ')})}>Change Nameservers</button></div><div className="ns-list">{domain.nameservers.map((ns,i)=><div className="ns-row" key={ns}><span className="ns-index">{i+1}</span><span className="ns-name">{ns}</span><span className="ns-state"><Badge tone="success">Configured</Badge></span></div>)}</div></div><div className="card"><div className="card-header"><h2>DNS Zone</h2></div><div className="card-body">Managed externally. Registrar nameservers are managed here; DNS record CRUD is deferred.</div></div></div>{domain.caps.supportsChildHosts&&<><div className="section-title"><h2>Registered Hosts</h2><p>Advanced · Child nameservers</p></div><div className="card"><div className="host-row"><span className="ns-name">ns1.{domain.name}</span><span>1.2.3.4</span><span style={{marginLeft:'auto'}}><button className="btn ghost small">View details</button><button className="btn ghost small">Change IP</button></span></div></div></>}</>}
function Privacy({domain}){if(!domain.caps.supportsPrivacy)return <Empty title="Privacy is not supported for this TLD"/>;return <div className="card"><div className="card-header"><h2>ID Shield / Domain Privacy</h2><Badge tone="success">Active</Badge></div><div className="setting-row"><div className="setting-copy"><strong>Privacy protection</strong><span>Registrant contact details are protected where registry policy allows.</span></div><button className="switch on"/></div><div className="card-body"><Def label="Renewal price" value="$3.99 / year"/><Def label="Auto-renew" value="Enabled"/><Def label="Associated charge" value="INV-2026-0912"/></div></div>}
function Security({domain,updateDomain,setModal}){
  const protectedCount=(domain.transferLock==='locked'?1:0)+(domain.caps.supportsAuthCode?1:0)+1;
  return <><section className="security-posture card"><div className="security-posture-copy"><span className="eyebrow">Security posture</span><h2>{protectedCount}/3 protections active</h2><p>Transfer controls and sensitive credentials are isolated from the domain lifecycle.</p></div><div className="security-ring"><strong>{protectedCount}</strong><span>of 3</span></div></section><div className="security-control-grid"><SecurityCard icon="⌁" eyebrow="Transfer lock" title={domain.transferLock==='locked'?'Locked':'Unlocked'} text={domain.transferLock==='locked'?'Transfers away are blocked until explicitly unlocked.':'This domain can currently be transferred away.'} action={domain.caps.supportsTransferLock?<button className="btn small" onClick={()=>updateDomain({transferLock:domain.transferLock==='locked'?'unlocked':'locked'})}>{domain.transferLock==='locked'?'Unlock domain':'Lock domain'}</button>:<Badge>Unsupported</Badge>}/><SecurityCard icon="⌘" eyebrow="Authorization code" title={domain.caps.supportsAuthCode?'Protected':'Unavailable'} text={domain.caps.supportsAuthCode?'Re-authentication is required before reveal or copy.':'Authorization code is not exposed for this domain.'} action={domain.caps.supportsAuthCode?<button className="btn small" onClick={()=>setModal(authModal())}>Get authorization code</button>:<Badge>Unsupported</Badge>}/><SecurityCard icon="◈" eyebrow="Account protection" title="2FA enabled" text="Sensitive registrar actions require an authenticated account session." action={<Badge tone="success">Protected</Badge>}/></div><div className="section-title"><div><span className="eyebrow">Sensitive actions</span><h2>Advanced security</h2></div></div><div className="card"><div className="setting-row"><div className="setting-copy"><strong>Domain Password</strong><span>Provider-specific advanced credential.</span></div><button className="btn small">Update Domain Password</button></div></div></>
}
function SecurityCard({icon,eyebrow,title,text,action}){return <section className="security-control-card"><span className="security-control-icon">{icon}</span><div><span className="eyebrow">{eyebrow}</span><h3>{title}</h3><p>{text}</p></div>{action}</section>}

function DomainTransfers({domain,updateDomain,setModal}){
  const readiness=transferReadiness(domain);
  const toneClass=readiness.status==='ready'?'success':readiness.status==='processing'?'info':readiness.status==='blocked'?'warning':'';
  const checklist=[['Transfer Lock',domain.transferLock==='locked'?'Locked':'Unlocked',domain.transferLock==='unlocked'],['Authorization Code',domain.caps.supportsAuthCode?'Available after re-auth':'Unavailable',domain.caps.supportsAuthCode],['Transfer capability',domain.caps.supportsTransferOut?'Supported':'Unsupported',domain.caps.supportsTransferOut]];
  return <><section className={`transfer-state-hero card ${toneClass}`}><div><span className="eyebrow">Domain transfer</span><div className="transfer-state-title"><h2>{readiness.status==='processing'?'Transfer in progress':readiness.status==='ready'?'Ready to transfer out':readiness.status==='blocked'?'Action needed before transfer':'Transfer out unavailable'}</h2><Badge tone={toneClass}>{readiness.status}</Badge></div><p>{readiness.status==='processing'?'The registrar is processing this transfer. Status updates are reconciled automatically.':readiness.nextAction||'This registrar capability is unavailable.'}</p></div><div className="transfer-hero-actions">{domain.transferLock==='locked'&&domain.caps.supportsTransferLock&&<button className="btn" onClick={()=>updateDomain({transferLock:'unlocked'})}>Unlock domain</button>}{domain.caps.supportsAuthCode&&<button className="btn" onClick={()=>setModal(authModal())}>Get Auth Code</button>}{readiness.ready&&<button className="btn primary">Transfer Out</button>}{domain.transfer&&<button className="btn" onClick={()=>updateDomain({transfer:null,lifecycleStatus:'active'})}>Cancel Transfer</button>}</div></section><div className="transfer-layout"><section className="card"><div className="card-header"><div><span className="eyebrow">Readiness</span><h2>Transfer checklist</h2></div></div><div className="transfer-checklist">{checklist.map(([label,value,ok])=><div className="transfer-check" key={label}><span className={`check-state ${ok?'ok':'blocked'}`}>{ok?'✓':'!'}</span><div><strong>{label}</strong><span>{value}</span></div><Badge tone={ok?'success':'warning'}>{ok?'Ready':'Review'}</Badge></div>)}</div></section><section className="card"><div className="card-header"><div><span className="eyebrow">{domain.transfer?'Progress':'Current state'}</span><h2>{domain.transfer?'Transfer timeline':'No active transfer'}</h2></div></div><div className="card-body">{domain.transfer?<><Activity title="Started" detail="Transfer request created" time="Sep 18"/><Activity title="Authorization verified" detail="Registrar accepted authorization" time="Sep 18"/><Activity title="Registrar processing" detail="No action required" time="Now"/></>:<Empty title="No active transfer"/>}</div></section></div></>
}

function DomainSSL({domain}){if(!domain.caps.supportsSsl)return <Empty title="SSL products are unavailable for this domain"/>;return <div className="card"><div className="card-header"><h2>SSL certificates for {domain.name}</h2><button className="btn small card-action">＋ Order certificate</button></div><div className="table-wrap"><table><tbody><tr><td><strong>Standard DV</strong><div className="domain-sub">{domain.name}</div></td><td><Badge tone={domain.sslStatus==='active'?'success':'info'}>{domain.sslStatus}</Badge></td><td>Aug 18, 2027</td><td>Email / DNS</td></tr></tbody></table></div></div>}
function DomainBilling({domain}){return <div className="grid-2"><div className="card"><div className="card-header"><h2>Domain billing</h2></div><div className="card-body"><Def label="Last renewal" value={formatMoney(domain.price)}/><Def label="Privacy" value="$3.99"/></div></div><div className="card"><div className="card-header"><h2>Payment method</h2></div><div className="card-body"><strong>Visa •••• 4242</strong><p className="domain-sub">Expires 08/29</p></div></div></div>}
function DomainActivity(){return <div className="card"><div className="card-header"><h2>Domain Activity</h2></div><div className="card-body"><Activity title="Renewal" detail="Completed" time="Sep 21, 14:32"/><Activity title="Nameserver Update" detail="Completed" time="Sep 18, 12:14"/><Activity title="Transfer Lock" detail="Locked" time="Sep 17, 09:22"/></div></div>}
function authModal(){return {title:'Re-authenticate to reveal auth code',subtitle:'Sensitive credentials stay hidden until re-authentication succeeds.',body:'Password → Continue → Reveal / Copy'}}

function Transfers({openDomain}){
  return <><PageHeader title="Transfers" description="Track incoming and outgoing registrar transfers across your portfolio." actions={<button className="btn primary">＋ Transfer domain in</button>}/><section className="metrics transfer-metrics"><Metric label="In progress" value="1" note="Registrar processing"/><Metric label="Action required" value="0" note="Nothing waiting on you"/><Metric label="Ready to transfer" value="1" note="Unlocked and supported"/><Metric label="Completed" value="8" note="Last 12 months"/></section><section className="card transfer-portfolio-card"><div className="card-header"><div><span className="eyebrow">Active</span><h2>Current transfers</h2></div><span className="card-count">1</span></div><div className="table-wrap"><table><thead><tr><th>Domain</th><th>Direction</th><th>Status</th><th>Started</th><th>Latest update</th><th>Next action</th></tr></thead><tbody><tr className="clickable" onClick={()=>openDomain('d3','transfers')}><td><div className="domain-identity-cell"><span className="domain-monogram">O</span><span><strong>orbitlabs.dev</strong><span className="domain-sub">Labs</span></span></div></td><td>Transfer in</td><td><Badge tone="info">Processing</Badge></td><td>Sep 18, 2026</td><td>Registrar processing</td><td>No action required</td></tr></tbody></table></div></section><section className="transfer-guide"><span className="domain-action-icon">↔</span><div><strong>Transfers stay asynchronous</strong><p>Processing, action-required, completed, and failed states are shown without pretending registrar operations are instant.</p></div></section></>
}

function SSL(){return <><PageHeader title="SSL" description="Certificate products across all domains—not website HTTPS health monitoring." actions={<button className="btn primary">＋ Order certificate</button>}/><div className="card"><div className="table-wrap"><table><tbody>{['example.com','framekit.app','madebyacme.co'].map((d,i)=><tr key={d}><td><strong>{d}</strong></td><td>Standard DV</td><td><Badge tone={i===2?'info':'success'}>{i===2?'Pending':'Active'}</Badge></td><td>Aug {18+i}, 2027</td></tr>)}</tbody></table></div></div></>}
function Billing(){return <><PageHeader title="Billing" description="Payment methods, invoices, and upcoming domain renewals."/><div className="grid-2"><div className="card"><div className="card-header"><h2>Upcoming renewals</h2></div><div className="card-body"><Def label="northstar.io · Sep 26" value="$42.00 · Payment failed"/><Def label="orbitlabs.dev · Jan 11" value="$18.00 · Auto-renew off"/></div></div><div className="card"><div className="card-header"><h2>Payment method</h2></div><div className="card-body"><strong>Visa •••• 4242</strong></div></div></div></>}
function Workspace(){return <><PageHeader title="Workspace" description="Manage members and lightweight roles for Acme Studio." actions={<button className="btn primary">＋ Invite member</button>}/><div className="card"><div className="card-body"><Def label="Ibrahim Maher" value="Owner · Active"/><Def label="Sarah Chen" value="Admin · Active"/><Def label="Omar Ali" value="Member · Active"/></div></div></>}
function Settings(){return <><PageHeader title="Settings" description="Personal preferences and notification controls."/><div className="card"><div className="card-header"><h2>Notifications</h2></div>{['Domain expiration emails','Transfer updates','SSL updates','Product announcements'].map((x,i)=><div className="setting-row" key={x}><div className="setting-copy"><strong>{x}</strong><span>Configure notification delivery.</span></div><button className={`switch ${i<3?'on':''}`}/></div>)}</div></>}
function Search({cart,setCart,setRoute}){const [q,setQ]=useState('acme');const options=[[`${q||'acme'}.com`,14.99],[`${q||'acme'}.io`,42],[`${q||'acme'}.dev`,18]];return <div className="search-page"><div className="search-hero"><h1>Find your next domain</h1><p>Search availability, compare extensions, and register through your workspace.</p></div><div className="domain-search-box"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value.replace(/\..*/,''))}/><button className="btn primary">Search</button></div><div className="search-results">{options.map(([d,p])=><div className="search-result" key={d}><div><div className="domain">{d}</div><div className="availability">Available</div></div><div className="price"><strong>{formatMoney(p)}</strong><span>/ first year</span></div><button className="btn small primary" onClick={()=>setCart(c=>c.some(x=>x.domain===d)?c:[...c,{domain:d,price:p}])}>Add</button></div>)}</div>{cart.length>0&&<div className="card" style={{marginTop:16}}><div className="card-body"><strong>{cart.length} domain{cart.length>1?'s':''} in cart</strong><button className="btn primary" style={{float:'right'}} onClick={()=>setRoute('checkout')}>Checkout</button></div></div>}</div>}
function Checkout({cart,setCart,setRoute}){const total=cart.reduce((s,i)=>s+i.price,0);if(!cart.length)return <Empty title="Your cart is empty"/>;return <><PageHeader title="Checkout" description="Review registrant details and payment before completing registration."/><div className="checkout-grid"><div><div className="checkout-section"><div className="head">Registrant contact</div><div className="body"><div className="form-grid"><div className="field"><label>First name</label><input defaultValue="Ibrahim"/></div><div className="field"><label>Last name</label><input defaultValue="Maher"/></div><div className="field full"><label>Email</label><input defaultValue="ibrahim@example.com"/></div></div></div></div></div><aside className="card order-summary"><div className="card-header"><h2>Order summary</h2></div><div className="card-body">{cart.map(i=><div className="summary-line" key={i.domain}><span>{i.domain}</span><strong>{formatMoney(i.price)}</strong></div>)}<div className="summary-line total"><span>Total</span><span>{formatMoney(total)}</span></div><button className="btn primary" style={{width:'100%',marginTop:14}} onClick={()=>{setCart([]);setRoute('domains')}}>Complete purchase</button></div></aside></div></>}
function Empty({title}){return <div className="empty-state"><div className="empty-icon">◌</div><h3>{title}</h3><p>This state is intentionally explicit instead of exposing unsupported registrar actions.</p></div>}
function Modal({config,close}){return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className="modal"><div className="modal-head"><h2>{config.title}</h2><p>{config.subtitle}</p></div><div className="modal-body"><p>{config.body}</p></div><div className="modal-actions"><button className="btn" onClick={close}>Cancel</button><button className="btn primary" onClick={close}>Continue</button></div></div></div>}
