import AppLayout from '@/Layouts/AppLayout';
import PageHeader from '@/Components/PageHeader';
import { Head, Link, router, useForm } from '@inertiajs/react';

export default function Show({ certificate, activity, notice, error }: { certificate: any; activity: any[]; notice?: string | null; error?: string | null }) {
    const email = useForm({ approver_email: '', confirm_email: '' });
    const reissue = useForm({ csr: '', confirm: false });
    const cancel = useForm({ confirm: false });
    const post = (name: string) => router.post(route(name, certificate.id), {}, { preserveScroll: true });

    return <AppLayout title="SSL Certificate"><Head title="SSL Certificate"/><PageHeader eyebrow="SSL" title={certificate.domain} description="Certificate lifecycle and validation status."/>
        <section className="max-w-3xl rounded-xl border border-[#e5e5e5] bg-white p-5">
            <dl className="grid gap-4 text-sm sm:grid-cols-2">{[['Product', certificate.product], ['Status', certificate.status], ['Validation', certificate.validation_type], ['Approver email', certificate.approver_email], ['Created', certificate.created_at], ['Issued', certificate.issued_at || 'Not issued'], ['Expires', certificate.expires_at || 'Not issued'], ['Last synced', certificate.provider_synced_at || 'Not synced']].map(([k, v]) => <div key={k}><dt className="text-[#737373]">{k}</dt><dd className="font-medium">{v}</dd></div>)}</dl>
            {notice && <p className="mt-5 rounded-md bg-emerald-50 p-3 text-sm">{notice}</p>}{error && <p className="mt-5 rounded-md bg-red-50 p-3 text-sm text-red-800">{error}</p>}
            <div className="mt-6 flex flex-wrap gap-3"><button onClick={() => post('ssl.refresh')} className="rounded-md bg-[#171717] px-4 py-2 text-sm text-white">Refresh Status</button>{certificate.actions.resend_approver_email && <button onClick={() => post('ssl.resend-approver-email')} className="rounded-md border px-4 py-2 text-sm">Resend validation email</button>}{certificate.actions.resend_fulfillment_email && <button onClick={() => post('ssl.resend-fulfillment-email')} className="rounded-md border px-4 py-2 text-sm">Resend certificate email</button>}<Link href={route('ssl')} className="px-2 py-2 text-sm underline">Back</Link></div>
            {certificate.actions.change_approver_email && <form onSubmit={e => { e.preventDefault(); email.post(route('ssl.approver-email', certificate.id)); }} className="mt-6 space-y-3 border-t pt-5"><h2 className="font-semibold">Change approver email</h2><p className="text-sm text-[#737373]">Current: {certificate.approver_email}</p><input type="email" required placeholder="New provider-approved email" value={email.data.approver_email} onChange={e => email.setData('approver_email', e.target.value)} className="w-full rounded-md border p-2"/><input type="email" required placeholder="Confirm new email" value={email.data.confirm_email} onChange={e => email.setData('confirm_email', e.target.value)} className="w-full rounded-md border p-2"/><button className="rounded-md border px-4 py-2 text-sm">Confirm email change</button></form>}
            {certificate.actions.reissue && <form onSubmit={e => { e.preventDefault(); reissue.post(route('ssl.reissue', certificate.id)); }} className="mt-6 space-y-3 border-t pt-5"><h2 className="font-semibold">Reissue certificate</h2><textarea required placeholder="Paste CSR only — never a private key" value={reissue.data.csr} onChange={e => reissue.setData('csr', e.target.value)} className="min-h-40 w-full rounded-md border p-2 font-mono text-xs"/><label className="flex gap-2 text-sm"><input type="checkbox" checked={reissue.data.confirm} onChange={e => reissue.setData('confirm', e.target.checked)}/>I confirm this reissue request.</label><button className="rounded-md border px-4 py-2 text-sm">Request reissue</button></form>}
            {certificate.actions.cancel && <form onSubmit={e => { e.preventDefault(); cancel.post(route('ssl.cancel', certificate.id)); }} className="mt-6 space-y-3 border-t pt-5"><h2 className="font-semibold text-red-700">Cancel certificate</h2><label className="flex gap-2 text-sm"><input type="checkbox" checked={cancel.data.confirm} onChange={e => cancel.setData('confirm', e.target.checked)}/>I understand this cancels the certificate order.</label><button className="rounded-md bg-red-700 px-4 py-2 text-sm text-white">Cancel certificate</button></form>}
            {!!activity.length && <div className="mt-6 border-t pt-5"><h2 className="font-semibold">Activity</h2><ul className="mt-3 space-y-2 text-sm">{activity.map(item => <li key={item.id}>{item.label} <span className="text-[#737373]">— {item.status}</span></li>)}</ul></div>}
        </section>
    </AppLayout>;
}
