[program:domain-saas-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/domain-saas/current/artisan queue:work redis --sleep=3 --tries=1 --timeout=160 --max-time=3600
directory=/var/www/domain-saas/current
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/supervisor/domain-saas-worker.log
stopwaitsecs=190
