import { router } from '@inertiajs/react';
import { FormEvent, useState } from 'react';

type Zone = { status: string; assigned_nameservers: string[] | null; delegated: boolean; ambiguous: boolean; provider_synced_at: string | null };
type Record = { id: string; type: string; name: string; content?: string; data?: { priority?: number; weight?: number; port?: number; target?: string; flags?: number; tag?: string; value?: string }; ttl: number; priority?: number; proxied?: boolean; proxiable?: boolean };
type Form = { type: string; name: string; content: string; ttl: number; proxied: boolean; priority: string; weight: string; port: string; target: string; flags: string; tag: string; value: string };
const types = ['A', 'AAAA', 'CNAME', 'MX', 'TXT', 'SRV', 'CAA'];
const blank: Form = { type: 'A', name: '@', content: '', ttl: 1, proxied: false, priority: '0', weight: '0', port: '0', target: '', flags: '0', tag: 'issue', value: '' };
const ttlOptions = [1, 60, 120, 300, 600, 1800, 3600, 7200, 14400, 28800, 43200, 86400];

export default function DnsPanel({ domainId, domainName, zone, records, error }: { domainId: number; domainName: string; zone: Zone | null; records: Record[]; error?: string | null }) {
    const [editing, setEditing] = useState<Record | 'new' | null>(null);
    const [deleting, setDeleting] = useState<Record | null>(null);
    const [form, setForm] = useState<Form>(blank);
    const [errors, setErrors] = useState<{ [key: string]: string }>({});
    const [busy, setBusy] = useState(false);
    const change = (field: keyof Form, value: string | number | boolean) => setForm({ ...form, [field]: value });
    const open = (record: Record | 'new') => {
        setEditing(record); setErrors({});
        setForm(record === 'new' ? blank : { type: record.type, name: record.name === domainName ? '@' : record.name, content: record.content ?? '', ttl: record.ttl, proxied: !!record.proxied, priority: String(record.data?.priority ?? record.priority ?? 0), weight: String(record.data?.weight ?? 0), port: String(record.data?.port ?? 0), target: record.data?.target ?? '', flags: String(record.data?.flags ?? 0), tag: record.data?.tag ?? 'issue', value: record.data?.value ?? '' });
    };
    const submit = (event: FormEvent) => {
        event.preventDefault(); setBusy(true); setErrors({});
        const options = { preserveScroll: true, onError: (value: { [key: string]: string }) => { setErrors(value); setBusy(false); }, onSuccess: () => { setEditing(null); setBusy(false); } };
        const payload = { ...form, priority: Number(form.priority), weight: Number(form.weight), port: Number(form.port), flags: Number(form.flags) };
        if (editing === 'new') router.post(route('domains.dns.records.store', domainId), payload, options);
        else if (editing) router.patch(route('domains.dns.records.update', [domainId, editing.id]), payload, options);
    };
    const refresh = () => router.post(route('domains.dns.sync', domainId), {}, { preserveScroll: true });

    return <section className="rounded-xl border border-[#e5e5e5] bg-white p-5">
        <div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">DNS Records</h2>{zone && <button type="button" onClick={refresh} className="rounded-md border px-3 py-2 text-sm">Refresh Status</button>}</div>
        {!zone && <div className="mt-4 space-y-3"><p className="text-sm">DNS is not hosted by this platform.</p><button type="button" onClick={() => router.post(route('domains.dns.connect', domainId))} className="rounded-md bg-[#171717] px-4 py-2 text-sm text-white">Connect DNS</button><p className="text-sm text-amber-900">Connecting will change registrar nameservers and can affect existing website or email services.</p></div>}
        {zone && zone.status !== 'active' && <div className="mt-4 space-y-3 text-sm"><p className="font-medium">{zone.status === 'error' ? 'Action required' : 'Waiting for DNS delegation to activate'}</p><p>Cloudflare zone created, but nameserver delegation still needs confirmation.</p><p>Assigned nameservers:</p><ul className="list-inside list-disc font-mono">{(zone.assigned_nameservers ?? []).map((ns) => <li key={ns}>{ns}</li>)}</ul><p>Registrar delegation: {zone.delegated ? 'confirmed' : 'not yet confirmed'}. Cloudflare activation: {zone.status}.</p><p>Refresh status to reconcile changes. Do not create another zone.</p>{zone.assigned_nameservers?.length && !zone.delegated && <button type="button" onClick={() => router.post(route('domains.dns.connect', domainId))} className="rounded-md border px-3 py-2">Confirm delegation</button>}</div>}
        {zone?.status === 'active' && <div className="mt-4"><div className="flex flex-wrap justify-between gap-2"><p className="text-sm">Cloudflare DNS is active. Registrar nameservers are managed separately.</p><button type="button" onClick={() => open('new')} disabled={zone.ambiguous} className="rounded-md bg-[#171717] px-3 py-2 text-sm text-white disabled:opacity-50">Add Record</button></div>
            {zone.ambiguous && <p role="alert" className="mt-3 rounded-md bg-amber-50 p-3 text-sm">A DNS change needs confirmation. Refresh status before another change.</p>}
            {error && <p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}
            <div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="py-2">Type</th><th>Name</th><th>Content</th><th>TTL</th><th>Proxy</th><th></th></tr></thead><tbody>{records.map((record) => <tr key={record.id} className="border-b"><td className="py-3">{record.type}</td><td className="pr-3 font-mono">{record.name === domainName ? '@' : record.name}</td><td className="max-w-xs break-all pr-3 font-mono">{record.content ?? (record.data ? Object.values(record.data).join(' ') : '')}</td><td>{record.ttl === 1 ? 'Auto' : `${record.ttl}s`}</td><td>{record.proxiable ? (record.proxied ? 'Proxied' : 'DNS only') : '—'}</td><td className="whitespace-nowrap text-right">{types.includes(record.type) && <><button type="button" onClick={() => open(record)} disabled={zone.ambiguous} className="mr-3 underline disabled:opacity-50">Edit</button><button type="button" onClick={() => setDeleting(record)} disabled={zone.ambiguous} className="text-red-700 underline disabled:opacity-50">Delete</button></>}</td></tr>)}</tbody></table>{records.length === 0 && !error && <p className="py-4 text-sm text-[#737373]">No DNS records found.</p>}</div>
        </div>}
        {editing && <div className="mt-5 rounded-lg border p-4"><h3 className="font-medium">{editing === 'new' ? 'Add Record' : 'Edit Record'}</h3><form onSubmit={submit} className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm">Type<select value={form.type} disabled={editing !== 'new'} onChange={(e) => change('type', e.target.value)} className="mt-1 block w-full rounded-md border p-2">{types.map((type) => <option key={type}>{type}</option>)}</select></label><label className="text-sm">Name<input value={form.name} onChange={(e) => change('name', e.target.value)} required className="mt-1 block w-full rounded-md border p-2" /></label>
            {!['SRV', 'CAA'].includes(form.type) && <label className="text-sm sm:col-span-2">{form.type === 'TXT' ? 'Text' : 'Content'}<input value={form.content} onChange={(e) => change('content', e.target.value)} required className="mt-1 block w-full rounded-md border p-2" /></label>}
            {form.type === 'SRV' && <>{(['priority', 'weight', 'port'] as const).map((field) => <label key={field} className="text-sm">{field}<input type="number" min="0" max="65535" value={form[field]} onChange={(e) => change(field, e.target.value)} required className="mt-1 block w-full rounded-md border p-2" /></label>)}<label className="text-sm">Target<input value={form.target} onChange={(e) => change('target', e.target.value)} required className="mt-1 block w-full rounded-md border p-2" /></label></>}
            {form.type === 'CAA' && <><label className="text-sm">Flags<input type="number" min="0" max="255" value={form.flags} onChange={(e) => change('flags', e.target.value)} required className="mt-1 block w-full rounded-md border p-2" /></label><label className="text-sm">Tag<select value={form.tag} onChange={(e) => change('tag', e.target.value)} className="mt-1 block w-full rounded-md border p-2"><option>issue</option><option>issuewild</option><option>iodef</option></select></label><label className="text-sm sm:col-span-2">Value<input value={form.value} onChange={(e) => change('value', e.target.value)} required className="mt-1 block w-full rounded-md border p-2" /></label></>}
            {form.type === 'MX' && <label className="text-sm">Priority<input type="number" min="0" max="65535" value={form.priority} onChange={(e) => change('priority', e.target.value)} required className="mt-1 block w-full rounded-md border p-2" /></label>}
            <label className="text-sm">TTL<select value={form.proxied && ['A', 'AAAA', 'CNAME'].includes(form.type) ? 1 : form.ttl} disabled={form.proxied && ['A', 'AAAA', 'CNAME'].includes(form.type)} onChange={(e) => change('ttl', Number(e.target.value))} className="mt-1 block w-full rounded-md border p-2 disabled:opacity-50">{ttlOptions.map((ttl) => <option value={ttl} key={ttl}>{ttl === 1 ? 'Auto' : `${ttl} seconds`}</option>)}</select></label>
            {['A', 'AAAA', 'CNAME'].includes(form.type) && <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.proxied} disabled={editing !== 'new' && editing.proxiable === false} onChange={(e) => change('proxied', e.target.checked)} />Proxied</label>}
            {Object.keys(errors).length > 0 && <p role="alert" className="text-sm text-red-700 sm:col-span-2">{Object.values(errors)[0]}</p>}
            <div className="flex gap-2 sm:col-span-2"><button type="submit" disabled={busy} className="rounded-md bg-[#171717] px-4 py-2 text-sm text-white disabled:opacity-50">Save</button><button type="button" onClick={() => setEditing(null)} className="rounded-md border px-4 py-2 text-sm">Cancel</button></div></form></div>}
        {deleting && <div role="dialog" aria-modal="true" aria-label="Delete DNS record" className="mt-5 rounded-lg border border-red-200 p-4"><h3 className="font-medium">Delete DNS record?</h3><p className="mt-2 break-all text-sm">{deleting.type} · {deleting.name} · {deleting.content ?? Object.values(deleting.data ?? {}).join(' ')}</p><div className="mt-4 flex gap-2"><button type="button" onClick={() => setDeleting(null)} className="rounded-md border px-4 py-2 text-sm">Cancel</button><button type="button" onClick={() => router.delete(route('domains.dns.records.destroy', [domainId, deleting.id]), { data: { confirm: true }, onSuccess: () => setDeleting(null) })} className="rounded-md bg-red-700 px-4 py-2 text-sm text-white">Delete</button></div></div>}
    </section>;
}
