import AdminLayout from '@/Layouts/AdminLayout';
import { router } from '@inertiajs/react';

const hidden = new Set(['user', 'customer', 'order', 'payments', 'domain', 'domain_record', 'registration_order', 'dns', 'activity']);
function display(value: unknown): string { if (value === null || value === undefined || value === '') return '—'; if (typeof value === 'boolean') return value ? 'Yes' : 'No'; if (Array.isArray(value)) return value.some(v => typeof v === 'object') ? `${value.length} record(s)` : value.join(', '); if (typeof value === 'object') return 'Linked'; return String(value); }

export default function Detail(props: any) {
    const record = props[props.resource];
    const operation = record.activity?.find((item: any) => ['domain_registration', 'domain_renewal'].includes(item.operation) && item.status === 'ambiguous');
    const reconcile = props.resource === 'domain' ? ['domain', record.id] : props.resource === 'transfer' ? ['transfer', record.id] : props.resource === 'certificate' ? ['ssl', record.id] : operation ? [operation.operation === 'domain_registration' ? 'registration' : 'renewal', operation.id] : null;
    const sections: Record<string, any[]> = { ...(props.related ?? {}) };
    for (const key of ['payments', 'activity']) if (Array.isArray(record[key])) sections[key] = record[key];
    for (const key of ['order', 'domain', 'domain_record', 'registration_order', 'dns', 'ssl']) if (record[key] && !Array.isArray(record[key])) sections[key] = [record[key]];
    return <AdminLayout title={props.title}><div className="grid gap-4 lg:grid-cols-[1fr_320px]"><section className="rounded-xl border bg-white"><div className="border-b px-5 py-4 font-semibold">Safe record details</div><dl className="grid gap-px bg-neutral-100 sm:grid-cols-2">{Object.entries(record).filter(([key]) => !hidden.has(key)).map(([key, value]) => <div key={key} className="bg-white px-5 py-4"><dt className="text-xs uppercase tracking-wide text-neutral-500">{key.replaceAll('_', ' ')}</dt><dd className="mt-1 break-words text-sm font-medium">{display(value)}</dd></div>)}</dl></section><aside className="space-y-4"><div className="rounded-xl border bg-white p-5"><h2 className="text-sm font-semibold">Customer</h2><p className="mt-2 text-sm">{record.customer?.name ?? '—'}</p><p className="text-xs text-neutral-500">{record.customer?.email}</p></div>{reconcile && <div className="rounded-xl border bg-white p-5"><h2 className="text-sm font-semibold">Safe action</h2><p className="my-2 text-xs text-neutral-500">Reads current provider state. It never repeats a provider write.</p><button onClick={() => router.post(route('admin.reconcile', reconcile))} className="rounded-lg bg-black px-3 py-2 text-sm text-white">Refresh / Reconcile</button></div>}</aside></div>{Object.entries(sections).map(([name, rows]) => <section key={name} className="mt-4 rounded-xl border bg-white"><h2 className="border-b px-5 py-3 text-sm font-semibold capitalize">{name.replaceAll('_', ' ')}</h2><div className="divide-y">{rows.length ? rows.map((row: any, index: number) => <div key={row.id ?? index} className="grid gap-2 px-5 py-3 text-xs sm:grid-cols-4">{Object.entries(row).filter(([key]) => !['user_id', 'domain_id'].includes(key)).slice(0, 10).map(([key, value]) => <span key={key}><span className="text-neutral-400">{key.replaceAll('_', ' ')}: </span>{display(value)}</span>)}</div>) : <p className="p-5 text-sm text-neutral-500">No records.</p>}</div></section>)}</AdminLayout>;
}
