import AdminLayout from '@/Layouts/AdminLayout';
import { Link, router } from '@inertiajs/react';

export default function Operations({ operations, alerts, filters }: any) {
    const change = (key: string, value: string) => router.get(route('admin.operations'), { ...filters, [key]: value });

    return <AdminLayout title="Operations">
        <div className="mb-5 grid gap-3 sm:grid-cols-4">{Object.entries(alerts).map(([label, count]) => <div key={label} className={`rounded-xl border bg-white p-4 ${Number(count) ? 'border-amber-300' : ''}`}><p className="text-xs capitalize text-neutral-500">{label.replaceAll('_', ' ')}</p><p className="mt-1 text-2xl font-semibold">{String(count)}</p></div>)}</div>
        <div className="mb-4 flex flex-wrap gap-2">
            <select aria-label="Operation status" className="rounded-lg border bg-white px-3 py-2 text-sm" value={filters.status ?? ''} onChange={e => change('status', e.target.value)}><option value="">All statuses</option>{['pending', 'completed', 'failed', 'ambiguous', 'action_required'].map(s => <option key={s}>{s}</option>)}</select>
            <select aria-label="Operation category" className="rounded-lg border bg-white px-3 py-2 text-sm" value={filters.category ?? ''} onChange={e => change('category', e.target.value)}><option value="">All categories</option>{['registration', 'renewal', 'nameservers', 'security', 'transfer', 'ssl', 'dns'].map(s => <option key={s}>{s}</option>)}</select>
            <select aria-label="Operation source" className="rounded-lg border bg-white px-3 py-2 text-sm" value={filters.source ?? ''} onChange={e => change('source', e.target.value)}><option value="">Registrar + DNS</option><option value="registrar">Registrar</option><option value="dns">DNS</option></select>
        </div>
        <div className="overflow-x-auto rounded-xl border bg-white"><table className="min-w-full text-left text-sm"><thead className="border-b bg-neutral-50 text-xs uppercase text-neutral-500"><tr>{['Category', 'Operation', 'Resource', 'Customer', 'Provider', 'Status', 'Started', 'Completed', 'Age', ''].map(h => <th key={h} className="px-4 py-3 font-medium">{h}</th>)}</tr></thead><tbody className="divide-y">{operations.data.map((op: any) => <tr key={`${op.source}-${op.operation_id}`} className={['ambiguous', 'action_required'].includes(op.status) ? 'bg-amber-50' : ''}><td className="px-4 py-3">{op.category}</td><td className="px-4 py-3">{op.operation}</td><td className="px-4 py-3">{op.resource || '—'}</td><td className="px-4 py-3">{op.customer}</td><td className="px-4 py-3">{op.provider}</td><td className="px-4 py-3">{op.status}</td><td className="px-4 py-3">{op.started_at}</td><td className="px-4 py-3">{op.completed_at ?? '—'}</td><td className="px-4 py-3">{Math.max(0, Math.floor((Date.now() - new Date(op.started_at).getTime()) / 60000))}m</td><td className="px-4 py-3">{op.source === 'dns' ? <button className="text-xs font-medium underline" onClick={() => router.post(route('admin.reconcile', ['dns', op.id]))}>Refresh</button> : ['domain_registration', 'domain_renewal'].includes(op.operation) ? <button className="text-xs font-medium underline" onClick={() => router.post(route('admin.reconcile', [op.operation === 'domain_registration' ? 'registration' : 'renewal', op.id]))}>Reconcile</button> : null}</td></tr>)}</tbody></table></div>
        <div className="mt-4 flex gap-2">{operations.links.map((link: any, i: number) => <Link key={i} href={link.url ?? '#'} className={`rounded-lg border bg-white px-3 py-2 text-sm ${link.active ? 'bg-black text-white' : ''} ${!link.url ? 'pointer-events-none opacity-40' : ''}`} dangerouslySetInnerHTML={{ __html: link.label }} />)}</div>
        <p className="mt-4 text-xs text-neutral-500">Transaction IDs, raw provider messages, checksums, credentials, and raw payloads are intentionally hidden.</p>
    </AdminLayout>;
}
