import AdminLayout from '@/Layouts/AdminLayout';
import { router, useForm } from '@inertiajs/react';

function State({ value }: { value: boolean }) { return <span className={`rounded-full px-2 py-1 text-xs ${value ? 'bg-emerald-50 text-emerald-700' : 'bg-neutral-100 text-neutral-600'}`}>{value ? 'Configured' : 'Not configured'}</span>; }

export default function Providers({ providers, balance, settings, status }: any) {
    const form = useForm({ ...settings, password: '' });

    return <AdminLayout title="Providers">
        <div className="grid gap-4 lg:grid-cols-3">{Object.entries(providers).map(([name, provider]: [string, any]) => <section key={name} className="rounded-xl border bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-semibold capitalize">{name}</h2><State value={provider.configured} /></div><dl className="mt-5 space-y-3 text-sm">{Object.entries(provider).filter(([key]) => key !== 'configured').map(([key, value]) => <div key={key} className="flex justify-between gap-4"><dt className="text-neutral-500">{key.replaceAll('_', ' ')}</dt><dd className="max-w-44 break-words text-right">{typeof value === 'boolean' ? (value ? 'Yes' : 'No') : String(value ?? 'Never')}</dd></div>)}</dl>{name === 'onlinenic' && <div className="mt-5 border-t pt-4"><p className="text-xs text-neutral-500">Account balance</p><p className="mt-1 text-xl font-semibold">{balance?.unavailable || !balance ? 'Unavailable' : `${balance.amount} ${balance.currency}`}</p>{balance?.checked_at && <p className="text-xs text-neutral-400">Checked {balance.checked_at}</p>}<button onClick={() => router.post(route('admin.providers.balance'))} className="mt-3 min-h-11 rounded-lg border px-3 py-2 text-xs font-medium">Refresh balance</button></div>}</section>)}</div>
        <section className="mt-6 max-w-3xl rounded-xl border bg-white p-5 sm:p-6"><div className="mb-5"><h2 className="text-lg font-semibold">OnlineNIC configuration</h2><p className="mt-1 text-sm text-neutral-600">Update the server-side TCP account. Secrets are encrypted and never returned to the browser.</p></div>{status && <p className="mb-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800" role="status">{status}</p>}<form onSubmit={(event) => { event.preventDefault(); form.put(route('admin.providers.onlinenic.update'), { onSuccess: () => form.reset('password') }); }} className="grid gap-4 sm:grid-cols-2">{([['host', 'Host'], ['port', 'Port'], ['client_id', 'Account ID'], ['account_currency', 'Account currency'], ['customer_billing_currency', 'Customer currency'], ['registrant_contact_id', 'Registrant contact'], ['admin_contact_id', 'Admin contact'], ['tech_contact_id', 'Tech contact'], ['billing_contact_id', 'Billing contact']] as const).map(([name, label]) => <label key={name} className="block text-sm font-medium text-neutral-800">{label}<input value={form.data[name] as string} onChange={(event) => form.setData(name, event.target.value)} className="mt-1 min-h-11 w-full rounded-md border-neutral-300 text-sm shadow-sm focus:border-black focus:ring-black" /><span className="mt-1 block text-xs text-red-600">{form.errors[name]}</span></label>)}<label className="block text-sm font-medium text-neutral-800">Password {settings.password_configured && <span className="font-normal text-neutral-500">(configured; leave blank to keep)</span>}<input type="password" autoComplete="new-password" value={form.data.password} onChange={(event) => form.setData('password', event.target.value)} className="mt-1 min-h-11 w-full rounded-md border-neutral-300 text-sm shadow-sm focus:border-black focus:ring-black" /><span className="mt-1 block text-xs text-red-600">{form.errors.password}</span></label><div className="sm:col-span-2 flex items-center justify-between gap-4 border-t pt-4"><p className="text-xs text-neutral-500">The current adapter authenticates with Account ID + Password, not a separate API key.</p><button disabled={form.processing} className="min-h-11 rounded-lg bg-black px-4 py-2 text-sm font-medium text-white disabled:opacity-50">{form.processing ? 'Saving…' : 'Save settings'}</button></div></form></section>
        <p className="mt-5 text-xs text-neutral-500">Paymob and Cloudflare credentials remain server-managed until their secure settings contracts are defined.</p>
    </AdminLayout>;
}
