import AdminLayout from '@/Layouts/AdminLayout';
import { router, useForm } from '@inertiajs/react';

function State({ value }: { value: boolean }) { return <span className={`rounded-full px-2 py-1 text-xs ${value ? 'bg-emerald-50 text-emerald-700' : 'bg-neutral-100 text-neutral-600'}`}>{value ? 'Configured' : 'Not configured'}</span>; }

function Field({ form, name, label, type = 'text' }: any) { return <label className="block text-sm font-medium text-neutral-800">{label}<input type={type} value={form.data[name] ?? ''} onChange={(event) => form.setData(name, event.target.value)} className="mt-1 min-h-11 w-full rounded-md border-neutral-300 text-sm shadow-sm focus:border-black focus:ring-black" /><span className="mt-1 block text-xs text-red-600">{form.errors[name]}</span></label>; }

export default function Providers({ providers, balance, settings, status }: any) {
    const form = useForm({ ...settings.onlinenic, password: '' });
    const paymob = useForm({ ...settings.paymob, secret_key: '', public_key: '', hmac_secret: '' });
    const cloudflare = useForm({ ...settings.cloudflare, api_token: '' });

    return <AdminLayout title="Providers">
        <div className="grid gap-4 lg:grid-cols-3">{Object.entries(providers).map(([name, provider]: [string, any]) => <section key={name} className="rounded-xl border bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-semibold capitalize">{name}</h2><State value={provider.configured} /></div><dl className="mt-5 space-y-3 text-sm">{Object.entries(provider).filter(([key]) => key !== 'configured').map(([key, value]) => <div key={key} className="flex justify-between gap-4"><dt className="text-neutral-500">{key.replaceAll('_', ' ')}</dt><dd className="max-w-44 break-words text-right">{typeof value === 'boolean' ? (value ? 'Yes' : 'No') : String(value ?? 'Never')}</dd></div>)}</dl>{name === 'onlinenic' && <div className="mt-5 border-t pt-4"><p className="text-xs text-neutral-500">Account balance</p><p className="mt-1 text-xl font-semibold">{balance?.unavailable || !balance ? 'Unavailable' : `${balance.amount} ${balance.currency}`}</p>{balance?.checked_at && <p className="text-xs text-neutral-400">Checked {balance.checked_at}</p>}<button onClick={() => router.post(route('admin.providers.balance'))} className="mt-3 min-h-11 rounded-lg border px-3 py-2 text-xs font-medium">Refresh balance</button></div>}</section>)}</div>
        <section className="mt-6 max-w-3xl rounded-xl border bg-white p-5 sm:p-6"><div className="mb-5"><h2 className="text-lg font-semibold">OnlineNIC configuration</h2><p className="mt-1 text-sm text-neutral-600">Update the server-side TCP account. Secrets are encrypted and never returned to the browser.</p></div>{status && <p className="mb-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800" role="status">{status}</p>}<form onSubmit={(event) => { event.preventDefault(); form.put(route('admin.providers.onlinenic.update'), { onSuccess: () => form.reset('password') }); }} className="grid gap-4 sm:grid-cols-2">{([['host', 'Host'], ['port', 'Port'], ['client_id', 'Account ID'], ['account_currency', 'Account currency'], ['customer_billing_currency', 'Customer currency'], ['registrant_contact_id', 'Registrant contact'], ['admin_contact_id', 'Admin contact'], ['tech_contact_id', 'Tech contact'], ['billing_contact_id', 'Billing contact']] as const).map(([name, label]) => <label key={name} className="block text-sm font-medium text-neutral-800">{label}<input value={form.data[name] as string} onChange={(event) => form.setData(name, event.target.value)} className="mt-1 min-h-11 w-full rounded-md border-neutral-300 text-sm shadow-sm focus:border-black focus:ring-black" /><span className="mt-1 block text-xs text-red-600">{form.errors[name]}</span></label>)}<label className="block text-sm font-medium text-neutral-800">Password {settings.password_configured && <span className="font-normal text-neutral-500">(configured; leave blank to keep)</span>}<input type="password" autoComplete="new-password" value={form.data.password} onChange={(event) => form.setData('password', event.target.value)} className="mt-1 min-h-11 w-full rounded-md border-neutral-300 text-sm shadow-sm focus:border-black focus:ring-black" /><span className="mt-1 block text-xs text-red-600">{form.errors.password}</span></label><div className="sm:col-span-2 flex items-center justify-between gap-4 border-t pt-4"><p className="text-xs text-neutral-500">The current adapter authenticates with Account ID + Password, not a separate API key.</p><button disabled={form.processing} className="min-h-11 rounded-lg bg-black px-4 py-2 text-sm font-medium text-white disabled:opacity-50">{form.processing ? 'Saving…' : 'Save settings'}</button></div></form></section>
        <section className="mt-6 max-w-3xl rounded-xl border bg-white p-5 sm:p-6"><div className="mb-5"><h2 className="text-lg font-semibold">Paymob configuration</h2><p className="mt-1 text-sm text-neutral-600">Secrets are encrypted; blank secret fields keep the current values.</p></div><form onSubmit={(event) => { event.preventDefault(); paymob.put(route('admin.providers.paymob.update'), { onSuccess: () => paymob.reset('secret_key', 'public_key', 'hmac_secret') }); }} className="grid gap-4 sm:grid-cols-2"><Field form={paymob} name="base_url" label="Base URL" /><Field form={paymob} name="mode" label="Mode (test/live)" /><Field form={paymob} name="card_integration_id" label="Card integration ID" /><Field form={paymob} name="payment_expiration" label="Payment expiration (seconds)" /><Field form={paymob} name="notification_url" label="Notification URL" /><Field form={paymob} name="redirection_url" label="Redirection URL" /><Field form={paymob} name="secret_key" label={`Secret key${settings.paymob.secret_key_configured ? ' (configured)' : ''}`} type="password" /><Field form={paymob} name="public_key" label={`Public key${settings.paymob.public_key_configured ? ' (configured)' : ''}`} type="password" /><Field form={paymob} name="hmac_secret" label={`HMAC secret${settings.paymob.hmac_secret_configured ? ' (configured)' : ''}`} type="password" /><div className="sm:col-span-2 flex justify-end"><button disabled={paymob.processing} className="min-h-11 rounded-lg bg-black px-4 py-2 text-sm font-medium text-white disabled:opacity-50">{paymob.processing ? 'Saving…' : 'Save Paymob'}</button></div></form></section>
        <section className="mt-6 max-w-3xl rounded-xl border bg-white p-5 sm:p-6"><div className="mb-5"><h2 className="text-lg font-semibold">Cloudflare configuration</h2><p className="mt-1 text-sm text-neutral-600">The API token is encrypted and never returned to the browser.</p></div><form onSubmit={(event) => { event.preventDefault(); cloudflare.put(route('admin.providers.cloudflare.update'), { onSuccess: () => cloudflare.reset('api_token') }); }} className="grid gap-4 sm:grid-cols-2"><Field form={cloudflare} name="api_base" label="API base URL" /><Field form={cloudflare} name="account_id" label="Account ID" /><Field form={cloudflare} name="api_token" label={`API token${settings.cloudflare.api_token_configured ? ' (configured)' : ''}`} type="password" /><div className="sm:col-span-2 flex justify-end"><button disabled={cloudflare.processing} className="min-h-11 rounded-lg bg-black px-4 py-2 text-sm font-medium text-white disabled:opacity-50">{cloudflare.processing ? 'Saving…' : 'Save Cloudflare'}</button></div></form></section>
        <p className="mt-5 text-xs text-neutral-500">Changing credentials does not contact providers or validate them automatically. Use provider-specific health checks only when authorized.</p>
    </AdminLayout>;
}
